apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: mariadb
        labels:
          app: my-app
          env: backend
        image: jayash1845/backend:latest
        ports:
        - containerPort: 3306
      - name: backend
        labels: 
          app: my-app
          env: backend 
        image: jayash1845/backend:latest
        - containerPort: 3000
      - name: backend
        labels: 
          app: my-app 
          env: backend
        image: jayash1845/backend:latest
        - containerPort: 3000
