apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
  app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: backend
        image: jayash1845/backend:latest
        ports:
        - containerPort: 80